version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fleet
      MYSQL_USER: fleet
      MYSQL_PASSWORD: fleet
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 20

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  fleet:
    build: ./
    environment:
      FLEET_MYSQL_ADDRESS: mysql:3306
      FLEET_MYSQL_USERNAME: fleet
      FLEET_MYSQL_PASSWORD: fleet
      FLEET_MYSQL_DATABASE: fleet
      FLEET_REDIS_ADDRESS: redis:6379
      FLEET_SERVER_CERT: /run/secrets/fleet_cert
      FLEET_SERVER_KEY: /run/secrets/fleet_key
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_started
      redis:
        condition: service_started
    secrets:
      - fleet_cert
      - fleet_key

secrets:
  fleet_cert:
    file: ./certs/cert.pem
  fleet_key:
    file: ./certs/key.pem

volumes:
  mysql_data:
  redis_data:
